### ISSUE TITLE
Can not run USBHostMBed5 from M4 Core!

### ISSUE THREAD

**Issue by mjs513** [arduino-libraries/Arduino_USBHostMbed5#45]
While experimenting with my gamepad sketches I tried a simple test where I would send gamepad info from the M4 core to the M7 core and found that it would hang, i.e., loose Serial connectivity, and basically kills the Giga.  

For example sketches and detailed info see in the following forum post:
https://forum.arduino.cc/t/can-not-find-examples-for-usbhostserial/1182486/49

**Comment by facchinm** [comment]
Should now be fixed by a combination of [782ede3](https://github.com/arduino-libraries/Arduino_USBHostMbed5/commit/782ede3c1b31f8b0540b7edbb4458c9e00056ccf) and https://github.com/arduino/ArduinoCore-mbed/pull/774 .
The core containing the fixes will be available in the next few weeks but in the meantime it can already be tested using the git versions

**Comment by mjs513** [comment]
@facchinm  -  thanks will hang on a bit until the formal release.
